export const SELECT_ITEM_HEIGHT = 'SELECT_ITEM_HEIGHT';
export const SET_MODAL_COORDS = 'SET_MODAL_COORDS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SUBMIT_EVENTS = 'SUBMIT_EVENTS';
export const UPDATE_DAY = 'UPDATE_DAY';
